const groups=[
 {label:'品質指揮中心',items:[['dashboard','全球品質總覽','⌂'],['quality-intelligence','品質智慧中心','QI']]},
 {label:'現場檢測',items:[['inspection-studio','AI 檢測工作室','◫'],['review','人工復判中心','◉'],['alerts','異常處置中心','!']]},
 {label:'品質分析',items:[['equipment-yield','設備良率分析','⌁'],['stability','檢測穩定度分析','≈'],['spc','SPC 製程分析','⌗'],['recommend','工程標準推薦','◇'],['root-cause','AI 根因與改善','⌬']]},
 {label:'品質追溯',items:[['trace','產品缺陷追溯','◎'],['sn-report','SN 追蹤報表','#'],['equipment-report','設備追蹤報表','▣'],['batch','批次隔離與追蹤','⊘']]},
 {label:'全球部署',items:[['deployment-fleet','部署艦隊','◌'],['development','開發進度','↗'],['rollout','擴散進度','⇢'],['rollout-list','擴散進度表','≡'],['introduction','導入細則匯總表','✓']]},
 {label:'AI 管理',items:[['samples','樣本與標註管理','▧'],['datasets','資料集管理','◈'],['model-compare','模型驗證與比較','⇆'],['models','模型管理','AI'],['model-release','模型發布紀錄','↥']]},
 {label:'設備維運',items:[['station-health','工站健康監控','●'],['calibration','相機與光源校正','⊙'],['first-article','首件確認','Ⅰ'],['maintenance','維護紀錄','⚙']]},
 {label:'平台治理',items:[['reports','報表中心','▥'],['data-quality','資料品質監控','◆'],['task-center','匯入／匯出任務','⇅'],['integrations','系統介面管理','⌁'],['alarm-rules','警報規則管理','⚑']]},
 {label:'流程與系統管理',items:[['workflow','流程配置','⇄'],['users','用戶管理','♙'],['roles','角色管理','♜'],['menu','選單管理','☷'],['departments','部門管理','▤'],['positions','崗位管理','♟'],['lists','清單定義','☑'],['dictionary','字典管理','⌘'],['notices','通知公告','◉'],['logs','操作日誌','≣'],['login-logs','登入日誌','↳']]}
];
const stations=[
 {id:'ST10',name:'ST10-VISION-INSPECTION',line:'LINE-03 · F2',product:'1001-AL-HOUSING',count:'12,480',yield:'98.42%',delta:'+0.36%',ng:197,review:28,status:'正常',model:'VIS-2.4.1'},
 {id:'ST14',name:'ST14-SURFACE-CHECK',line:'LINE-03 · F2',product:'1001-AL-HOUSING',count:'11,906',yield:'96.18%',delta:'-1.24%',ng:455,review:76,status:'警告',model:'VIS-2.3.8'},
 {id:'ST21',name:'ST21-BURR-INSPECTION',line:'LINE-07 · F3',product:'1048-BRACKET',count:'8,221',yield:'94.76%',delta:'-2.08%',ng:431,review:42,status:'嚴重',model:'VIS-1.9.6'},
 {id:'ST08',name:'ST08-DIMENSION-CHECK',line:'LINE-01 · F1',product:'1032-SHAFT',count:'10,774',yield:'99.08%',delta:'+0.12%',ng:99,review:12,status:'正常',model:'VIS-3.1.0'},
 {id:'ST32',name:'ST32-FINAL-VISION',line:'LINE-11 · F4',product:'1065-COVER',count:'7,492',yield:'97.31%',delta:'-0.22%',ng:202,review:31,status:'正常',model:'VIS-2.7.2'}
];
const pageMeta={
 'quality-intelligence':['品質智慧中心','跨廠關聯品質事件、製程條件與改善成效'],'inspection-studio':['AI 檢測工作室','以無程式流程建立影像、檢查區域、模型與判定規則'],'deployment-fleet':['部署艦隊','管理各廠 Edge、相機、模型與配方的一致性'],
 review:['人工復判中心','處理 AI 判定不確定與需要品質確認的產品'],alerts:['異常處置中心','集中管理工站、品質與設備異常'],'root-cause':['AI 根因與改善','以人、機、料、法、環、測追蹤改善成效'],
 'equipment-yield':['設備良率分析','比較設備、模具與穴位的品質表現'],stability:['檢測穩定度分析','監控影像、模型與現場條件的波動'],spc:['SPC 製程分析','以統計管制辨識製程偏移'],recommend:['工程標準推薦','依生產證據提出可審核的改善建議'],
 trace:['產品缺陷追溯','從缺陷回溯產品、設備、工站與影像'], 'sn-report':['SN 追蹤報表','查詢單件產品的完整生產履歷'], 'equipment-report':['設備追蹤報表','追蹤設備版本、維護與品質結果'],batch:['批次隔離與追蹤','管理受影響產品範圍與放行'],
 development:['開發進度','管理新產品 AI 檢測方案的導入階段'],rollout:['擴散進度','掌握跨廠複製與上線狀態'],'rollout-list':['擴散進度表','逐站追蹤擴散任務與風險'],introduction:['導入細則匯總表','依企業標準查核工站導入準備'],
 samples:['樣本與標註管理','建立可稽核的圖片標註與品質審核流程'],datasets:['資料集管理','管理訓練、驗證、測試集與版本不可變性'],'model-compare':['模型驗證與比較','比較候選與正式模型，檢查 Critical 缺陷'],models:['模型管理','管理模型生命週期、適用範圍與部署狀態'],'model-release':['模型發布紀錄','追蹤分批發布、核准與回退事件'],
 'station-health':['工站健康監控','監控相機、光源、PLC、Edge 與版本一致性'],calibration:['相機與光源校正','保存校正參數、影像證據與到期狀態'],'first-article':['首件確認','換型後核對工單、配方、模型與品質核准'],maintenance:['維護紀錄','關聯清潔、保養、換刀、換模與良率事件'],
 reports:['報表中心','集中管理品質報表、圖片與排程匯出'],'data-quality':['資料品質監控','追蹤 SN、圖片、映射、回寫與跨系統一致性'],'task-center':['匯入／匯出任務','查看背景任務進度、錯誤明細與稽核結果'],integrations:['系統介面管理','監控 MES、SFC、QMS、ERP 與帳號同步'],'alarm-rules':['警報規則管理','設定門檻、適用範圍、通知與升級策略'],
 workflow:['流程配置','管理核准、復判、發布與異常流程'],users:['用戶管理','管理企業內部帳號與資料範圍'],roles:['角色管理','設定功能與資料存取權限'],menu:['選單管理','配置不同角色可見的系統功能'],departments:['部門管理','維護集團、廠區與部門組織'],positions:['崗位管理','定義工作職責、代理與簽核關係'],lists:['清單定義','維護現場表單、檢核項目與版本'],dictionary:['字典管理','管理全系統共用狀態與代碼'],notices:['通知公告','發布跨廠品質公告與到期提醒'],logs:['操作日誌','追蹤高風險操作與設定異動'],'login-logs':['登入日誌','追蹤帳號登入、裝置與異常存取']
};
const content=document.getElementById('content'),nav=document.getElementById('nav'),breadcrumb=document.getElementById('breadcrumb');
function renderNav(active){nav.innerHTML=groups.map(g=>`<div class="nav-group"><div class="nav-label">${g.label}</div>${g.items.map(i=>`<button class="nav-item ${active===i[0]?'active':''}" data-page="${i[0]}"><span class="nav-icon">${i[2]}</span>${i[1]}</button>`).join('')}</div>`).join('');nav.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));}
function head(title,sub,actions=true){return `<div class="page-head"><div><div class="eyebrow">AI QUALITY OPERATIONS</div><h1>${title}</h1><p>${sub}</p></div>${actions?`<div class="filters"><select class="select"><option>深圳一廠</option><option>全部廠區</option></select><select class="select"><option>今日</option><option>近 7 日</option><option>近 30 日</option></select><button class="button">匯出</button></div>`:''}</div>`}
function lineChart(){return `<div class="chart"><span class="axis-y" style="top:-5px">100%</span><span class="axis-y" style="top:46px">98%</span><span class="axis-y" style="top:94px">96%</span><span class="axis-y" style="top:142px">94%</span><span class="axis-y" style="top:190px">92%</span>${['00','04','08','12','16','20','24'].map((x,i)=>`<span class="axis-x" style="left:${i*16.66}%">${x}:00</span>`).join('')}<svg viewBox="0 0 800 238" preserveAspectRatio="none" aria-label="良率趨勢"><path d="M0 80 L65 74 L130 88 L195 68 L260 72 L325 58 L390 65 L455 50 L520 55 L585 43 L650 51 L715 36 L800 41" fill="none" stroke="#13a887" stroke-width="3"/><path d="M0 118 L65 108 L130 121 L195 96 L260 106 L325 89 L390 94 L455 72 L520 87 L585 69 L650 78 L715 61 L800 67" fill="none" stroke="#2d6cdf" stroke-width="2"/><path d="M0 132 L800 132" fill="none" stroke="#d94f5c" stroke-width="1.5" stroke-dasharray="6 5"/></svg></div>`}
function dailyChart(){return `<div class="daily-bars">${[['09/06',96.8],['09/07',97.1],['09/08',96.6],['09/09',97.4],['09/10',97.0],['09/11',97.7],['今日',97.46]].map((d,i)=>`<div class="day-bar"><strong>${d[1]}%</strong><i style="height:${34+(d[1]-95)*24}px" class="${i===6?'active':''}"></i><span>${d[0]}</span></div>`).join('')}</div>`}
function insightPanel(){return `<section class="insight-panel"><div class="insight-main"><div class="insight-signal"><span class="signal-orbit"><i></i></span><div><div class="insight-kicker">AI SHIFT BRIEF · 15:00</div><h2>整體良率穩定，但 ST21 已成為今日主要風險來源</h2><p>近 4 小時良率下降 2.08%，占全廠 NG 的 33.3%。異常集中在 MOLD-04／Cavity 03，與毛刺及漏焊影像特徵同步上升。</p></div></div><div class="insight-evidence"><div><span>分析可信度</span><strong>92%</strong></div><div><span>影響產品</span><strong>1,268</strong></div><div><span>建議處置時限</span><strong>30 min</strong></div></div><div class="insight-actions"><button onclick="stationDetail('ST21')">查看證據鏈</button><button onclick="go('alerts')">建立異常處置</button></div></div><div class="insight-daily"><div class="insight-daily-head"><div><span>總體良率趨勢 · 日</span><strong>7 日平均 97.15%</strong></div><span class="badge">穩定</span></div>${dailyChart()}</div></section>`}
function dashboard(){breadcrumb.textContent='總覽 / 首頁';content.innerHTML=head('品質營運總覽','即時掌握跨工站良率、異常與人工復判狀態')+`<div class="kpi-grid">
${[['總工站數量','32','28 在線 · 4 維護',''],['今日檢測數','50,873','較昨日 +4.8%','good'],['檢測良率','97.46%','較昨日 +0.42%','good'],['NG 數量','1,294','NG 率 2.54%','bad'],['人工復判 OK','189','AI 誤殺率 12.7%','warn'],['今日異常工站','3','1 嚴重 · 2 警告','bad']].map(k=>`<div class="kpi ${k[3]}"><div class="kpi-label">${k[0]}</div><div class="kpi-value">${k[1]}</div><div class="delta ${k[2].includes('+')?'up':''}">${k[2]}</div></div>`).join('')}</div>${insightPanel()}
<div class="grid-2"><section class="card"><div class="card-head"><div><h2>總體良率趨勢 · 小時</h2><span class="card-sub">最終良率與 AI 初判良率</span></div><div class="legend"><span><i style="background:#13a887"></i>最終良率</span><span><i style="background:#2d6cdf"></i>AI 初判</span><span><i style="background:#d94f5c"></i>目標 95.5%</span></div></div>${lineChart()}</section>
<section class="card"><div class="card-head"><div><h2>工站狀態總覽</h2><span class="card-sub">32 個啟用工站</span></div></div><div class="status-stack">${[['正常',25,78,'#13a887'],['警告',2,6,'#d78a19'],['嚴重',1,3,'#d94f5c'],['維護中',4,13,'#718196']].map(x=>`<div class="status-row"><span>${x[0]}</span><div class="progress"><span style="width:${x[2]}%;background:${x[3]}"></span></div><strong>${x[1]}</strong></div>`).join('')}</div><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><div class="card-head"><h2>復判佇列</h2><span class="badge amber"><span class="dot"></span>7 件即將逾時</span></div><div class="metric-strip"><div><span>待復判</span><strong>42</strong></div><div><span>最長等待</span><strong>08:41</strong></div></div></section></div>
<section class="card"><div class="card-head"><div><h2>各工站品質</h2><span class="card-sub">依異常等級與良率變動排序</span></div><button class="button" onclick="showToast('已套用異常優先排序')">異常優先</button></div><div class="table-wrap"><table class="station-table"><thead><tr><th>工站名稱</th><th>當前產品</th><th>今日檢測</th><th>檢測良率</th><th>良率變動</th><th>NG</th><th>復判 OK</th><th>狀態</th><th>模型版本</th></tr></thead><tbody>${stations.map(s=>`<tr data-station="${s.id}"><td><div class="station-name">${s.name}<small>${s.line}</small></div></td><td>${s.product}</td><td>${s.count}</td><td><strong>${s.yield}</strong></td><td class="${s.delta.startsWith('+')?'delta up':'delta down'}">${s.delta}</td><td>${s.ng}</td><td>${s.review}</td><td>${statusBadge(s.status)}</td><td>${s.model}</td></tr>`).join('')}</tbody></table></div></section>`;document.querySelectorAll('[data-station]').forEach(r=>r.onclick=()=>stationDetail(r.dataset.station));}
function statusBadge(s){const c=s==='正常'?'':s==='警告'?'amber':'red';return `<span class="badge ${c}"><span class="dot"></span>${s}</span>`}
function stationDetail(id){const s=stations.find(x=>x.id===id)||stations[0];breadcrumb.textContent=`首頁 / ${s.name}`;renderNav('dashboard');content.innerHTML=`<button class="back-button" onclick="go('dashboard')">← 返回首頁</button>`+head(s.name,`${s.line} · CNC-MILLING · ${s.product}`,false)+`<div class="metric-strip" style="margin-bottom:16px"><div><span>今日良率</span><strong>${s.yield}</strong></div><div><span>今日檢測</span><strong>${s.count}</strong></div><div><span>最終 NG</span><strong>${s.ng}</strong></div><div><span>復判 OK</span><strong>${s.review}</strong></div></div><div class="page-grid"><section class="card span-8"><div class="card-head"><div><h2>最新檢測影像</h2><span class="card-sub">SN 260912-A10482 · 14:32:18</span></div><span class="badge red"><span class="dot"></span>NG · SCRATCH</span></div><div class="inspection-visual"><div class="part-shape"></div><div class="defect-box"></div></div></section><section class="card span-4"><div class="card-head"><h2>工站健康狀態</h2>${statusBadge(s.status)}</div><div class="timeline"><div class="timeline-item"><i class="timeline-dot"></i><div><strong>工業相機 CAM-02</strong><p>曝光與對焦正常 · 12 MP</p></div></div><div class="timeline-item"><i class="timeline-dot"></i><div><strong>Edge AI 節點</strong><p>推論 P95 326 ms · GPU 48%</p></div></div><div class="timeline-item"><i class="timeline-dot"></i><div><strong>PLC S7-1500</strong><p>通訊正常 · 8 ms</p></div></div><div class="timeline-item"><i class="timeline-dot"></i><div><strong>模型 ${s.model}</strong><p>核准版本 · VISUAL-RCP-18</p></div></div></div></section><section class="card span-8"><div class="card-head"><h2>工站良率趨勢</h2><span class="card-sub">最近 24 小時</span></div>${lineChart()}</section><section class="card span-4"><div class="card-head"><h2>主要缺陷</h2></div><div class="status-stack">${[['SCRATCH',84,58,'#d94f5c'],['BURR',47,34,'#d78a19'],['DENT',29,22,'#2d6cdf'],['CONTAMINATION',18,14,'#13a887']].map(x=>`<div class="status-row"><span>${x[0]}</span><div class="progress"><span style="width:${x[2]}%;background:${x[3]}"></span></div><strong>${x[1]}</strong></div>`).join('')}</div></section></div>`;}
function generic(page){const [title,sub]=pageMeta[page];breadcrumb.textContent=`功能選單 / ${title}`;let special='';if(page==='development'||page==='rollout'){special=`<div class="kpi-grid">${[['計畫項目','24','本季範圍',''],['進行中','9','3 項接近里程碑','good'],['已完成','11','完成率 45.8%','good'],['逾期','3','需負責人處理','bad'],['暫停','1','等待設備到貨','warn'],['平均週期','32 天','較上季 -4 天','good']].map(k=>`<div class="kpi ${k[3]}"><div class="kpi-label">${k[0]}</div><div class="kpi-value">${k[1]}</div><div class="delta">${k[2]}</div></div>`).join('')}</div>`}else if(page==='equipment-yield'||page==='stability'||page==='spc'){special=`<div class="grid-2"><section class="card"><div class="card-head"><h2>${page==='equipment-yield'?'設備良率趨勢':page==='stability'?'檢測穩定度控制圖':'製程管制圖'}</h2><span class="card-sub">最近 24 小時</span></div>${lineChart()}</section><section class="card"><div class="card-head"><h2>分析摘要</h2><span class="badge amber">2 項需注意</span></div><div class="timeline"><div class="timeline-item"><i class="timeline-dot"></i><div><strong>ST21 良率低於管制線</strong><p>集中於 MOLD-04 的 Cavity 03</p></div></div><div class="timeline-item"><i class="timeline-dot"></i><div><strong>ST14 影像重拍率上升</strong><p>建議檢查低角度光源強度</p></div></div><div class="timeline-item"><i class="timeline-dot"></i><div><strong>其餘設備維持穩定</strong><p>未偵測到模型漂移</p></div></div></div></section></div>`}content.innerHTML=head(title,sub)+special+tableFor(page);bindActions();}
function tableFor(page){const management=['users','roles','menu','departments','dictionary','logs','workflow'].includes(page);const rows=management?[['U-001','林 品質主管','集團品質中心','啟用','2026-09-12 14:28'],['U-014','王 品質工程師','深圳一廠品質部','啟用','2026-09-12 13:42'],['U-032','Chen Wei','AI 平台團隊','啟用','2026-09-12 11:18'],['U-078','陳 設備工程師','設備維護部','停用','2026-08-28 09:02']]:[['QA-260912-0018','1001-AL-HOUSING','ST21-BURR-INSPECTION','Cavity 03','SCRATCH','嚴重','處理中'],['QA-260912-0017','1001-AL-HOUSING','ST14-SURFACE-CHECK','Cavity 02','DENT','警告','待確認'],['QA-260912-0016','1048-BRACKET','ST10-VISION-INSPECTION','Cavity 01','BURR','一般','已完成'],['QA-260912-0015','1032-SHAFT','ST08-DIMENSION-CHECK','—','MISSING-FEATURE','嚴重','工程複核']];return `<section class="card"><div class="toolbar"><div class="tabs"><button class="tab active">全部</button><button class="tab">待處理</button><button class="tab">已完成</button></div><button class="button primary" data-action>${management?'新增資料':'建立案件'}</button></div><div class="table-wrap"><table class="data-table"><thead><tr>${(management?['編號','名稱','所屬範圍','狀態','最後異動']:['案件編號','產品','工站','穴位','缺陷','嚴重度','狀態']).map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td>${i===r.length-1?`<span class="badge ${x.includes('停用')||x.includes('複核')?'red':x.includes('待')?'amber':''}">${x}</span>`:x}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`}
function bindActions(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>showToast('已建立示範項目'));document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{t.parentNode.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');showToast(`已切換至「${t.textContent}」`)})}
function go(page){location.hash=page;renderNav(page);if(page==='dashboard')dashboard();else generic(page);document.getElementById('sidebar').classList.remove('open');window.scrollTo(0,0)}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}window.showToast=showToast;window.go=go;
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');const dialog=document.getElementById('searchDialog');document.getElementById('searchBtn').onclick=()=>dialog.showModal();document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();dialog.showModal()}});dialog.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>{dialog.close();go(b.dataset.goto)});go(location.hash.slice(1)||'dashboard');
